import type { Metadata } from 'next';
import '@cbhq/cds-icons/fonts/web/icon-font.css';
import '@cbhq/cds-web/defaultFontStyles';
import '@cbhq/cds-web/globalStyles';

export const metadata: Metadata = {
  title: 'CDS Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
