export const enabledRoutes = [
  'Accordion',
  'Button',
  'Text',
  // 'AlertBasic',
  // 'AlphaSelect',
  // 'AlphaSelectChip',
  // 'AlphaTabbedChips',
  // 'AreaChart',
  // 'Avatar',
  // 'AvatarButton',
  // 'Axis',
  // 'Banner',
  // 'BarChart',
  // 'Box',
  // 'BrowserBar',
  // 'ButtonGroup',
  // 'Card',
  // 'Carousel',
  // 'CartesianChart',
  // 'Checkbox',
  // 'CheckboxCell',
  // 'Chip',
  // 'Coachmark',
  // 'Combobox',
  // 'ControlGroup',
  // 'Divider',
  // 'Dot',
  // 'Group',
  // 'InputChip',
  // 'InputStack',
  // 'Legend',
  // 'Link',
  // 'ListCell',
  // 'Pressable',
  // 'RadioCell',
  // 'SelectChip',
  // 'SlideButton',
  // 'StepperHorizontal',
  // 'StepperVertical',
  // 'StickyFooter',
  // 'Switch',
  // 'Tabs',
  // 'Tag',
];
