/**
 * Generates Icon Code Connect files for both web and mobile packages, driven
 * entirely by the icon component sets in the Figma CDS Components file.
 *
 * Rather than one Code Connect template file per icon, each package gets a single
 * Code Connect *batch* integration (https://developers.figma.com/docs/code-connect/batch-files/)
 * in its `icons/__figma__/` directory:
 *
 *   - `icons.figma.batch.ts`   A shared, parser-less template. It has no `// url=`
 *                              metadata comments and reads per-icon data (the icon
 *                              name) from `figma.batch`, which the Figma runtime
 *                              populates from each entry in the JSON file below.
 *   - `icons.figma.batch.json` Lists every icon as a `{ name, url, source, component }`
 *                              entry. Each entry publishes as its own Code Connect
 *                              document, exactly as the old per-icon files did.
 *
 * Active/Inactive-suffixed variants (e.g. "ui/bellActive") are legacy names — they
 * collapse onto the base icon's single entry (<Icon name="bell" />), since the
 * active state is expressed via the shared `active` prop instead of a distinct name.
 *
 * Called automatically by `icons:sync-icons`, but can also be run standalone:
 *
 *   yarn nx run icons:sync-icon-code-connect
 *
 * Environment:
 *   FIGMA_ACCESS_TOKEN  Required. Figma personal access token.
 */

import { getFileComponentSets } from '@cds/figma-api';
import fs from 'node:fs';
import path from 'node:path';

// The Figma CDS component-library file key — this is where the Icon component
// instances live in Figma, distinct from the icons asset file used by sync-icons.
const CODE_CONNECT_FIGMA_FILE_KEY = 'k5CtyJccNQUGMI5bI4lJ2g';
const FIGMA_BASE_URL = `https://www.figma.com/design/${CODE_CONNECT_FIGMA_FILE_KEY}/CDS-Components`;

// Names of the two batch files written into each icons/__figma__ directory.
const BATCH_TEMPLATE_FILE = 'icons.figma.batch.ts';
const BATCH_JSON_FILE = 'icons.figma.batch.json';

// ─── Name helpers ─────────────────────────────────────────────────────────────

// Icons in the Figma file are prefixed with "ui/" or "nav/" (e.g. "ui/bellActive").
// Strips the prefix, converts to camelCase, then strips legacy Active/Inactive
// suffixes so all variants render as the base icon name in code.
function toIconName(rawName: string): string {
  return rawName
    .trim()
    .replace(/^(?:ui|nav)\//, '')
    .trim()
    .replace(/[-_\s]+(.)/g, (_, c: string) => c.toUpperCase())
    .replace(/^(.)/, (c: string) => c.toLowerCase())
    .replace(/(?:Active|Inactive)$/, '');
}

// Whether a raw Figma set name carries a legacy Active/Inactive suffix.
function isLegacyVariant(rawName: string): boolean {
  return /(?:Active|Inactive)$/.test(rawName.replace(/^(?:ui|nav)\//, '').trim());
}

// Reads the canonical icon name list generated by sync-icons from
// packages/icons/src/IconName.ts, so we can drop any code-connect entries whose
// Figma name doesn't correspond to a real IconName.
function readValidIconNames(repoRoot: string): Set<string> {
  const iconNameFile = path.join(repoRoot, 'packages/icons/src/IconName.ts');
  const contents = fs.readFileSync(iconNameFile, 'utf-8');
  const names = new Set<string>();
  for (const match of contents.matchAll(/'([^']+)'/g)) {
    names.add(match[1]);
  }
  return names;
}

// ─── File generation ──────────────────────────────────────────────────────────

type Target = {
  label: string;
  outDir: string;
  importPackage: string;
  sourcePath: string;
  idSuffix: string;
};

type ComponentSet = { name: string; node_id: string };

type Icon = { iconName: string; nodeId: string };

// Builds the shared batch template (`icons.figma.batch.ts`) for a target. Unlike
// a per-icon raw template, it carries no `// url=`/`// source=`/`// component=`
// metadata (those come from the JSON entries) and substitutes the icon name via
// `figma.batch.name`, which the Figma runtime resolves per entry at render time.
//
// The `example`/`id` lines embed `figma.code` and template-literal placeholders
// (`${figma.batch.name}`, `${size}`, …) that must remain literal in the output, so
// the file is assembled from single-quoted strings to avoid interpolating them here.
export function renderBatchTemplate(target: Target): string {
  return (
    `import figma from 'figma';\n` +
    `\n` +
    `const instance = figma.selectedInstance;\n` +
    `\n` +
    `const size = instance.getEnum('size', {\n` +
    `  xs: 'xs',\n` +
    `  s: 's',\n` +
    `  m: 'm',\n` +
    `  l: 'l',\n` +
    `});\n` +
    `\n` +
    `const active = instance.getBoolean('active');\n` +
    `\n` +
    `// eslint-disable-next-line no-restricted-exports\n` +
    `export default {\n` +
    '  example: figma.code`<Icon name="${figma.batch.name}" size="${size}"' +
    "${active ? ' active' : ''} />`,\n" +
    `  imports: ['import { Icon } from "${target.importPackage}"'],\n` +
    '  id: `icon-${figma.batch.name}' +
    target.idSuffix +
    '`,\n' +
    `  metadata: { nestable: true },\n` +
    `};\n`
  );
}

// Builds the batch JSON (`icons.figma.batch.json`) for a target: one entry per
// icon, each pointing the shared template at a Figma node URL. `name` is the
// custom field consumed by the template via `figma.batch.name`.
export function renderBatchJson(target: Target, icons: Icon[]): string {
  const data = {
    templateFile: `./${BATCH_TEMPLATE_FILE}`,
    components: icons.map(({ iconName, nodeId }) => ({
      name: iconName,
      url: `${FIGMA_BASE_URL}?node-id=${nodeId.replace(':', '-')}`,
      source: target.sourcePath,
      component: 'Icon',
    })),
  };
  return `${JSON.stringify(data, null, 2)}\n`;
}

function generateFiles(target: Target, icons: Icon[]): number {
  // The two batch files are always overwritten, so we only need the dir to exist.
  fs.mkdirSync(target.outDir, { recursive: true });
  fs.writeFileSync(
    path.join(target.outDir, BATCH_TEMPLATE_FILE),
    renderBatchTemplate(target),
    'utf-8',
  );
  fs.writeFileSync(
    path.join(target.outDir, BATCH_JSON_FILE),
    renderBatchJson(target, icons),
    'utf-8',
  );
  console.log(`  [${target.label}] batch template + JSON written (${icons.length} icons).`);
  return icons.length;
}

// ─── Dedupe ───────────────────────────────────────────────────────────────────

// Collapses raw component sets to one canonical node per icon name. When several
// sets map to the same name, the base (non-Active/Inactive) variant wins; the
// input is pre-sorted so the fallback is deterministic.
function dedupeByIconName(
  iconSets: ComponentSet[],
  validIconNames: Set<string>,
): { icons: Icon[]; skipped: { rawName: string; iconName: string }[] } {
  const chosen = new Map<string, { nodeId: string; isBase: boolean }>();
  const skipped: { rawName: string; iconName: string }[] = [];

  for (const { name, node_id } of iconSets) {
    const iconName = toIconName(name);
    if (!validIconNames.has(iconName)) {
      skipped.push({ rawName: name, iconName });
      continue;
    }
    const isBase = !isLegacyVariant(name);
    const existing = chosen.get(iconName);
    // Prefer a base variant over a legacy one; otherwise keep the first seen.
    if (!existing || (isBase && !existing.isBase)) {
      chosen.set(iconName, { nodeId: node_id, isBase });
    }
  }

  const icons = [...chosen.entries()]
    .map(([iconName, { nodeId }]) => ({ iconName, nodeId }))
    .sort((a, b) => a.iconName.localeCompare(b.iconName));

  return { icons, skipped };
}

// ─── Exported function ────────────────────────────────────────────────────────

export function makeTargets(repoRoot: string): Target[] {
  return [
    {
      label: 'web',
      outDir: path.join(repoRoot, 'packages/web/src/icons/__figma__'),
      importPackage: '@coinbase/cds-web/icons',
      sourcePath: 'packages/web/src/icons/Icon.tsx',
      idSuffix: '',
    },
    {
      label: 'mobile',
      outDir: path.join(repoRoot, 'packages/mobile/src/icons/__figma__'),
      importPackage: '@coinbase/cds-mobile/icons',
      sourcePath: 'packages/mobile/src/icons/Icon.tsx',
      idSuffix: '-mobile',
    },
  ];
}

export async function syncIconCodeConnect(repoRoot: string) {
  console.log('\nSyncing icon Code Connect entries…');
  console.log('Fetching Figma component sets…');
  const { meta } = await getFileComponentSets(CODE_CONNECT_FIGMA_FILE_KEY);
  const allSets = (meta?.component_sets ?? []) as ComponentSet[];
  const iconSets = allSets
    .filter(({ name }) => /^(?:ui|nav)\//.test(name))
    .sort((a, b) => toIconName(a.name).localeCompare(toIconName(b.name)));
  console.log(`  Found ${iconSets.length} icon component sets.`);

  const validIconNames = readValidIconNames(repoRoot);
  console.log(`  Loaded ${validIconNames.size} valid icon names from IconName.ts`);

  const { icons, skipped } = dedupeByIconName(iconSets, validIconNames);
  console.log(`  ${icons.length} unique icons after dedupe.`);
  if (skipped.length > 0) {
    console.log(`  ${skipped.length} entries skipped (Figma name has no matching IconName):`);
    for (const { rawName, iconName } of skipped) {
      console.log(`    - "${rawName}" → "${iconName}"`);
    }
  }

  console.log('\nGenerating Code Connect batch files…');
  for (const target of makeTargets(repoRoot)) {
    generateFiles(target, icons);
    console.log(`  Written to ${path.relative(repoRoot, target.outDir)}`);
  }

  console.log('\n✅ Code Connect batch files generated.');
}

// ─── CLI entry point ──────────────────────────────────────────────────────────

const MONOREPO_ROOT = process.env.PROJECT_CWD ?? process.env.NX_MONOREPO_ROOT;

if (MONOREPO_ROOT) {
  syncIconCodeConnect(MONOREPO_ROOT).catch((err: unknown) => {
    console.error('Unexpected error:', err);
    process.exit(1);
  });
}
