/**
 * Generates Icon Code Connect files for both web and mobile packages, driven
 * entirely by the icon component sets in the Figma CDS Components file.
 *
 * Each icon component set (prefixed "ui/" or "nav/") gets its own parser-less
 * Code Connect template file (`<iconName>.figma.ts`) in the package's
 * `icons/__figma__/` directory. Active/Inactive-suffixed variants
 * (e.g. "ui/bellActive") are legacy names — they collapse onto the base icon's
 * single template (<Icon name="bell" />), since the active state is expressed
 * via the shared `active` prop instead of a distinct name.
 *
 * Called automatically by `icons:sync-icons`, but can also be run standalone:
 *
 *   yarn nx run icons:sync-icon-code-connect
 *
 * Environment:
 *   FIGMA_ACCESS_TOKEN  Required. Figma personal access token.
 */

import { getFileComponentSets } from '@cds/figma-api';
import fs from 'node:fs';
import path from 'node:path';

// The Figma CDS component-library file key — this is where the Icon component
// instances live in Figma, distinct from the icons asset file used by sync-icons.
const CODE_CONNECT_FIGMA_FILE_KEY = 'k5CtyJccNQUGMI5bI4lJ2g';
const FIGMA_BASE_URL = `https://www.figma.com/design/${CODE_CONNECT_FIGMA_FILE_KEY}/CDS-Components`;

// Files in each icons/__figma__ directory that are NOT generated per-icon
// templates and must never be deleted by the cleanup step.
const PRESERVE = new Set<string>([]);

// ─── Name helpers ─────────────────────────────────────────────────────────────

// Icons in the Figma file are prefixed with "ui/" or "nav/" (e.g. "ui/bellActive").
// Strips the prefix, converts to camelCase, then strips legacy Active/Inactive
// suffixes so all variants render as the base icon name in code.
function toIconName(rawName: string): string {
  return rawName
    .trim()
    .replace(/^(?:ui|nav)\//, '')
    .trim()
    .replace(/[-_\s]+(.)/g, (_, c: string) => c.toUpperCase())
    .replace(/^(.)/, (c: string) => c.toLowerCase())
    .replace(/(?:Active|Inactive)$/, '');
}

// Whether a raw Figma set name carries a legacy Active/Inactive suffix.
function isLegacyVariant(rawName: string): boolean {
  return /(?:Active|Inactive)$/.test(rawName.replace(/^(?:ui|nav)\//, '').trim());
}

// Reads the canonical icon name list generated by sync-icons from
// packages/icons/src/IconName.ts, so we can drop any code-connect entries whose
// Figma name doesn't correspond to a real IconName.
function readValidIconNames(repoRoot: string): Set<string> {
  const iconNameFile = path.join(repoRoot, 'packages/icons/src/IconName.ts');
  const contents = fs.readFileSync(iconNameFile, 'utf-8');
  const names = new Set<string>();
  for (const match of contents.matchAll(/'([^']+)'/g)) {
    names.add(match[1]);
  }
  return names;
}

// ─── File generation ──────────────────────────────────────────────────────────

type Target = {
  label: string;
  outDir: string;
  importPackage: string;
  sourcePath: string;
  idSuffix: string;
};

type ComponentSet = { name: string; node_id: string };

type Icon = { iconName: string; nodeId: string };

// Builds the full content of one parser-less Code Connect template file.
// The `example` line embeds a `figma.code` literal whose `${...}` placeholders are
// evaluated by the Figma runtime (not here), so it's assembled via string
// concatenation to keep those placeholders literal in the output.
export function renderIconTemplate(target: Target, iconName: string, nodeId: string): string {
  const url = `${FIGMA_BASE_URL}?node-id=${nodeId.replace(':', '-')}`;
  const exampleLine =
    '  example: figma.code`<Icon name="' +
    iconName +
    "\" size=\"${size}\"${active ? ' active' : ''} />`,";

  return (
    `// url=${url}\n` +
    `// source=${target.sourcePath}\n` +
    `// component=Icon\n` +
    `import figma from 'figma';\n` +
    `\n` +
    `const instance = figma.selectedInstance;\n` +
    `\n` +
    `const size = instance.getEnum('size', {\n` +
    `  xs: 'xs',\n` +
    `  s: 's',\n` +
    `  m: 'm',\n` +
    `  l: 'l',\n` +
    `});\n` +
    `\n` +
    `const active = instance.getBoolean('active');\n` +
    `\n` +
    `// eslint-disable-next-line no-restricted-exports\n` +
    `export default {\n` +
    `${exampleLine}\n` +
    `  imports: ['import { Icon } from "${target.importPackage}"'],\n` +
    `  id: 'icon-${iconName}${target.idSuffix}',\n` +
    `  metadata: { nestable: true },\n` +
    `};\n`
  );
}

// Removes previously-generated per-icon template files (and the legacy
// single-file Icon.figma.tsx) from a target dir, preserving anything in PRESERVE.
function cleanTargetDir(outDir: string): void {
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
    return;
  }
  for (const file of fs.readdirSync(outDir)) {
    if (PRESERVE.has(file)) continue;
    if (file.endsWith('.figma.ts') || file === 'Icon.figma.tsx') {
      fs.unlinkSync(path.join(outDir, file));
    }
  }
}

function generateFiles(target: Target, icons: Icon[]): number {
  cleanTargetDir(target.outDir);
  for (const { iconName, nodeId } of icons) {
    const content = renderIconTemplate(target, iconName, nodeId);
    fs.writeFileSync(path.join(target.outDir, `${iconName}.figma.ts`), content, 'utf-8');
  }
  console.log(`  [${target.label}] ${icons.length} template files written.`);
  return icons.length;
}

// ─── Dedupe ───────────────────────────────────────────────────────────────────

// Collapses raw component sets to one canonical node per icon name. When several
// sets map to the same name, the base (non-Active/Inactive) variant wins; the
// input is pre-sorted so the fallback is deterministic.
function dedupeByIconName(
  iconSets: ComponentSet[],
  validIconNames: Set<string>,
): { icons: Icon[]; skipped: { rawName: string; iconName: string }[] } {
  const chosen = new Map<string, { nodeId: string; isBase: boolean }>();
  const skipped: { rawName: string; iconName: string }[] = [];

  for (const { name, node_id } of iconSets) {
    const iconName = toIconName(name);
    if (!validIconNames.has(iconName)) {
      skipped.push({ rawName: name, iconName });
      continue;
    }
    const isBase = !isLegacyVariant(name);
    const existing = chosen.get(iconName);
    // Prefer a base variant over a legacy one; otherwise keep the first seen.
    if (!existing || (isBase && !existing.isBase)) {
      chosen.set(iconName, { nodeId: node_id, isBase });
    }
  }

  const icons = [...chosen.entries()]
    .map(([iconName, { nodeId }]) => ({ iconName, nodeId }))
    .sort((a, b) => a.iconName.localeCompare(b.iconName));

  return { icons, skipped };
}

// ─── Exported function ────────────────────────────────────────────────────────

export function makeTargets(repoRoot: string): Target[] {
  return [
    {
      label: 'web',
      outDir: path.join(repoRoot, 'packages/web/src/icons/__figma__'),
      importPackage: '@coinbase/cds-web/icons/Icon',
      sourcePath: 'packages/web/src/icons/Icon.tsx',
      idSuffix: '',
    },
    {
      label: 'mobile',
      outDir: path.join(repoRoot, 'packages/mobile/src/icons/__figma__'),
      importPackage: '@coinbase/cds-mobile/icons/Icon',
      sourcePath: 'packages/mobile/src/icons/Icon.tsx',
      idSuffix: '-mobile',
    },
  ];
}

export async function syncIconCodeConnect(repoRoot: string) {
  console.log('\nSyncing icon Code Connect entries…');
  console.log('Fetching Figma component sets…');
  const { meta } = await getFileComponentSets(CODE_CONNECT_FIGMA_FILE_KEY);
  const allSets = (meta?.component_sets ?? []) as ComponentSet[];
  const iconSets = allSets
    .filter(({ name }) => /^(?:ui|nav)\//.test(name))
    .sort((a, b) => toIconName(a.name).localeCompare(toIconName(b.name)));
  console.log(`  Found ${iconSets.length} icon component sets.`);

  const validIconNames = readValidIconNames(repoRoot);
  console.log(`  Loaded ${validIconNames.size} valid icon names from IconName.ts`);

  const { icons, skipped } = dedupeByIconName(iconSets, validIconNames);
  console.log(`  ${icons.length} unique icons after dedupe.`);
  if (skipped.length > 0) {
    console.log(`  ${skipped.length} entries skipped (Figma name has no matching IconName):`);
    for (const { rawName, iconName } of skipped) {
      console.log(`    - "${rawName}" → "${iconName}"`);
    }
  }

  console.log('\nGenerating Code Connect template files…');
  for (const target of makeTargets(repoRoot)) {
    generateFiles(target, icons);
    console.log(`  Written to ${path.relative(repoRoot, target.outDir)}`);
  }

  console.log('\n✅ Code Connect template files generated.');
}

// ─── CLI entry point ──────────────────────────────────────────────────────────

const MONOREPO_ROOT = process.env.PROJECT_CWD ?? process.env.NX_MONOREPO_ROOT;

if (MONOREPO_ROOT) {
  syncIconCodeConnect(MONOREPO_ROOT).catch((err: unknown) => {
    console.error('Unexpected error:', err);
    process.exit(1);
  });
}
