import fs from 'node:fs';
import path from 'node:path';

const svgOutputPath = path.join(process.cwd(), 'packages', 'icons', 'src', 'svgs');
const nativeMapOutputPath = path.join(
  process.cwd(),
  'packages',
  'ui-mobile-playground',
  'src',
  '__generated__',
  'iconSvgMap.ts',
);

/**
 * Generates a React Native SVG map file that reads each SVG file content
 * and exports a map keyed by `${name}-${size}-${state}` with content strings.
 */
export const generateSvgMap = (): void => {
  console.log('Generating React Native SVG map...');

  // Read all SVG files from the output directory
  const svgFiles: string[] = fs
    .readdirSync(svgOutputPath)
    .filter((file: string) => file.endsWith('.svg'))
    .sort((a: string, b: string) => a.localeCompare(b));

  if (svgFiles.length === 0) {
    console.log('No SVG files found, skipping SVG map generation');
    return;
  }

  const mapEntries: string[] = [];

  for (const file of svgFiles) {
    const base: string = file.replace(/\.svg$/, '');
    const svgFilePath: string = path.join(svgOutputPath, file);

    // Read the SVG file content as string
    const svgContent: string = fs.readFileSync(svgFilePath, 'utf8');

    // Escape quotes and newlines for JavaScript string literal
    const escapedContent: string = svgContent
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r');

    mapEntries.push(`  '${base}': { content: "${escapedContent}" },`);
  }

  const header: string = `/**
 * DO NOT MODIFY
 * This file is generated by ui-mobile-playground/scripts/generateIconSvgMap.ts
 * 
 * Why this exists:
 * - Provides a static map of icon names to their SVG content for rendering Icons directly with react-native-svg components
 *
 * What this provides:
 * - A static map of iconName-12|16|24|32-active|inactive → { content: "svg-string" }
 *
 * Usage:
 * - Access SVG string content via: svgMap['icon-name-12-active'].content
 */`;

  const content: string = `${header}

export const svgMap: Record<string, SvgMapEntry> = {
${mapEntries.join('\n')}
} as const;

export type SvgMapEntry = { content: string };
export type SvgMap = Record<string, SvgMapEntry>;
export type SvgKey = keyof typeof svgMap;

export default svgMap;
`;

  // Ensure the output directory exists
  const outputDir: string = path.dirname(nativeMapOutputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Write the file
  fs.writeFileSync(nativeMapOutputPath, content, 'utf8');

  console.log(
    `Generated React Native SVG map with ${svgFiles.length} entries -> ${path.relative(
      process.cwd(),
      nativeMapOutputPath,
    )}`,
  );
};

generateSvgMap();
