import type { AccordionBaseProps } from '../accordion/Accordion';
import type {
  AccordionHeaderBaseProps,
  AccordionIconBaseProps,
  AccordionMediaBaseProps,
  AccordionTitleBaseProps,
} from '../accordion/AccordionHeader';
import type { AccordionItemBaseProps } from '../accordion/AccordionItem';
import type { AccordionPanelBaseProps } from '../accordion/AccordionPanel';
import type { ComboboxBaseProps } from '../alpha/combobox/Combobox';
import type { DataCardLayoutBaseProps } from '../alpha/data-card/DataCardLayout';
import type { AlphaSelectBaseProps } from '../alpha/select/Select';
import type { SelectChipBaseProps } from '../alpha/select-chip/SelectChip';
import type { TabbedChipsBaseProps } from '../alpha/tabbed-chips/TabbedChips';
import type { BannerBaseProps } from '../banner/Banner';
import type { AvatarButtonBaseProps } from '../buttons/AvatarButton';
import type { ButtonBaseProps } from '../buttons/Button';
import type { ButtonGroupBaseProps } from '../buttons/ButtonGroup';
import type { IconButtonBaseProps } from '../buttons/IconButton';
import type { IconCounterButtonBaseProps } from '../buttons/IconCounterButton';
import type { TileBaseProps } from '../buttons/Tile';
import type { TileButtonBaseProps } from '../buttons/TileButton';
import type { CardBaseProps } from '../cards/Card';
import type { CardBodyBaseProps } from '../cards/CardBody';
import type { CardFooterBaseProps } from '../cards/CardFooter';
import type { CardGroupBaseProps } from '../cards/CardGroup';
import type { CardRootBaseProps } from '../cards/CardRoot';
import type { ContentCardBaseProps } from '../cards/ContentCard/ContentCard';
import type { ContentCardBodyBaseProps } from '../cards/ContentCard/ContentCardBody';
import type { ContentCardFooterBaseProps } from '../cards/ContentCard/ContentCardFooter';
import type { ContentCardHeaderBaseProps } from '../cards/ContentCard/ContentCardHeader';
import type { LikeButtonBaseProps } from '../cards/LikeButton';
import type { MediaCardBaseProps } from '../cards/MediaCard/index';
import type { MediaCardLayoutBaseProps } from '../cards/MediaCard/MediaCardLayout';
import type { MessagingCardBaseProps } from '../cards/MessagingCard/index';
import type { CarouselBaseProps } from '../carousel/Carousel';
import type { CellBaseProps } from '../cells/Cell';
import type { CellAccessoryBaseProps } from '../cells/CellAccessory';
import type { ListCellBaseProps } from '../cells/ListCell';
import type { ListCellFallbackBaseProps } from '../cells/ListCellFallback';
import type { ChipBaseProps } from '../chips/ChipProps';
import type { InputChipBaseProps } from '../chips/InputChip';
import type { MediaChipBaseProps } from '../chips/MediaChip';
import type { CoachmarkBaseProps } from '../coachmark/Coachmark';
import type { CollapsibleBaseProps } from '../collapsible/Collapsible';
import type { CheckboxBaseProps } from '../controls/Checkbox';
import type { CheckboxCellBaseProps } from '../controls/CheckboxCell';
import type { ControlBaseProps } from '../controls/Control';
import type { ControlGroupBaseProps } from '../controls/ControlGroup';
import type { InputStackBaseProps } from '../controls/InputStack';
import type { RadioBaseProps } from '../controls/Radio';
import type { RadioCellBaseProps } from '../controls/RadioCell';
import type { SearchInputBaseProps } from '../controls/SearchInput';
import type { SelectOptionBaseProps } from '../controls/SelectOption';
import type { SwitchBaseProps } from '../controls/Switch';
import type { TextInputBaseProps } from '../controls/TextInput';
import type { CalendarBaseProps } from '../dates/Calendar';
import type { DateInputBaseProps } from '../dates/DateInput';
import type { DatePickerBaseProps } from '../dates/DatePicker';
import type { DotCountBaseProps } from '../dots/DotCount';
import type { DotStatusColorBaseProps } from '../dots/DotStatusColor';
import type { DotSymbolBaseProps } from '../dots/DotSymbol';
import type { DropdownBaseProps } from '../dropdown/Dropdown';
import type { IconBaseProps } from '../icons/Icon';
import type { DividerBaseProps } from '../layout/Divider';
import type { FallbackBaseProps } from '../layout/Fallback';
import type { SpacerBaseProps } from '../layout/Spacer';
import type { SpinnerBaseProps } from '../loaders/Spinner';
import type { AvatarBaseProps } from '../media/Avatar';
import type { RemoteImageBaseProps } from '../media/RemoteImage';
import type { RemoteImageGroupBaseProps } from '../media/RemoteImageGroup';
import type { AnimatedCaretBaseProps } from '../motion/AnimatedCaret';
import type { ColorSurgeBaseProps } from '../motion/ColorSurge';
import type { ShakeBaseProps } from '../motion/Shake';
import type { MultiContentModuleBaseProps } from '../multi-content-module/MultiContentModule';
import type { NavigationBarBaseProps } from '../navigation/NavigationBar';
import type { NavigationTitleBaseProps } from '../navigation/NavigationTitle';
import type { NavigationTitleSelectBaseProps } from '../navigation/NavigationTitleSelect';
import type { SidebarBaseProps } from '../navigation/Sidebar';
import type { SidebarItemBaseProps } from '../navigation/SidebarItem';
import type { SidebarMoreMenuBaseProps } from '../navigation/SidebarMoreMenu';
import type { RollingNumberBaseProps } from '../numbers/RollingNumber/RollingNumber';
import type { AlertBaseProps } from '../overlays/Alert';
import type { FocusTrapBaseProps } from '../overlays/FocusTrap';
import type { FullscreenAlertBaseProps } from '../overlays/FullscreenAlert';
import type { HandleBarBaseProps } from '../overlays/handlebar/HandleBar';
import type { FullscreenModalBaseProps } from '../overlays/modal/FullscreenModal';
import type { FullscreenModalHeaderBaseProps } from '../overlays/modal/FullscreenModalHeader';
import type { FullscreenModalLayoutBaseProps } from '../overlays/modal/FullscreenModalLayout';
import type { ModalBaseProps } from '../overlays/modal/Modal';
import type { ModalBodyBaseProps } from '../overlays/modal/ModalBody';
import type { ModalFooterBaseProps } from '../overlays/modal/ModalFooter';
import type { ModalHeaderBaseProps } from '../overlays/modal/ModalHeader';
import type { ModalWrapperBaseProps } from '../overlays/modal/ModalWrapper';
import type { OverlayBaseProps } from '../overlays/overlay/Overlay';
import type { ToastBaseProps } from '../overlays/Toast';
import type { TooltipBaseProps } from '../overlays/tooltip/Tooltip';
import type { TooltipContentBaseProps } from '../overlays/tooltip/TooltipContent';
import type { TrayBaseProps } from '../overlays/tray/Tray';
import type { PageFooterBaseProps } from '../page/PageFooter';
import type { PageHeaderBaseProps } from '../page/PageHeader';
import type { PaginationBaseProps } from '../pagination/Pagination';
import type { SectionHeaderBaseProps } from '../section-header/SectionHeader';
import type { StepperBaseProps } from '../stepper/Stepper';
import type { InteractableBaseProps } from '../system/Interactable';
import type { TableBaseProps } from '../tables/Table';
import type { TableBodyBaseProps } from '../tables/TableBody';
import type { TableCaptionBaseProps } from '../tables/TableCaption';
import type { TableCellBaseProps } from '../tables/TableCell';
import type { TableCellFallbackBaseProps } from '../tables/TableCellFallback';
import type { TableFooterBaseProps } from '../tables/TableFooter';
import type { TableHeaderBaseProps } from '../tables/TableHeader';
import type { TableRowBaseProps } from '../tables/TableRow';
import type { SegmentedTabBaseProps } from '../tabs/SegmentedTab';
import type { SegmentedTabsBaseProps } from '../tabs/SegmentedTabs';
import type { TabIndicatorBaseProps } from '../tabs/TabIndicator';
import type { TabLabelBaseProps } from '../tabs/TabLabel';
import type { TabsBaseProps } from '../tabs/Tabs';
import type { TagBaseProps } from '../tag/Tag';
import type { TourBaseProps } from '../tour/Tour';
import type { LinkBaseProps } from '../typography/Link';
import type { ProgressBarBaseProps } from '../visualizations/ProgressBar';
import type { ProgressBarWithFixedLabelsBaseProps } from '../visualizations/ProgressBarWithFixedLabels';
import type { ProgressBarWithFloatLabelBaseProps } from '../visualizations/ProgressBarWithFloatLabel';
import type { ProgressCircleBaseProps } from '../visualizations/ProgressCircle';

/**
 * Config resolver that supports either static partial props object
 * or a function that receives component props and returns partial props.
 */
export type ConfigResolver<P> = Partial<P> | ((props: P) => Partial<P>);

/**
 * Component config for customization of default component props.
 * Use base props for config resolver typing so defaults are element-agnostic.
 */
export type ComponentConfig = {
  Accordion?: ConfigResolver<AccordionBaseProps>;
  AccordionHeader?: ConfigResolver<AccordionHeaderBaseProps>;
  AccordionIcon?: ConfigResolver<AccordionIconBaseProps>;
  AccordionItem?: ConfigResolver<AccordionItemBaseProps>;
  AccordionMedia?: ConfigResolver<AccordionMediaBaseProps>;
  AccordionPanel?: ConfigResolver<AccordionPanelBaseProps>;
  AccordionTitle?: ConfigResolver<AccordionTitleBaseProps>;
  Alert?: ConfigResolver<AlertBaseProps>;
  TabbedChips?: ConfigResolver<TabbedChipsBaseProps>;
  AnimatedCaret?: ConfigResolver<AnimatedCaretBaseProps>;
  Avatar?: ConfigResolver<AvatarBaseProps>;
  AvatarButton?: ConfigResolver<AvatarButtonBaseProps>;
  Banner?: ConfigResolver<BannerBaseProps>;
  Button?: ConfigResolver<ButtonBaseProps>;
  ButtonGroup?: ConfigResolver<ButtonGroupBaseProps>;
  Calendar?: ConfigResolver<CalendarBaseProps>;
  Card?: ConfigResolver<CardBaseProps>;
  CardBody?: ConfigResolver<CardBodyBaseProps>;
  CardFooter?: ConfigResolver<CardFooterBaseProps>;
  CardGroup?: ConfigResolver<CardGroupBaseProps>;
  CardRoot?: ConfigResolver<CardRootBaseProps>;
  Carousel?: ConfigResolver<CarouselBaseProps>;
  Cell?: ConfigResolver<CellBaseProps>;
  CellAccessory?: ConfigResolver<CellAccessoryBaseProps>;
  Chip?: ConfigResolver<ChipBaseProps>;
  Checkbox?: ConfigResolver<CheckboxBaseProps<string>>;
  CheckboxCell?: ConfigResolver<CheckboxCellBaseProps<string>>;
  Coachmark?: ConfigResolver<CoachmarkBaseProps>;
  Collapsible?: ConfigResolver<CollapsibleBaseProps>;
  ColorSurge?: ConfigResolver<ColorSurgeBaseProps>;
  Combobox?: ConfigResolver<ComboboxBaseProps>;
  ContentCard?: ConfigResolver<ContentCardBaseProps>;
  ContentCardBody?: ConfigResolver<ContentCardBodyBaseProps>;
  ContentCardFooter?: ConfigResolver<ContentCardFooterBaseProps>;
  ContentCardHeader?: ConfigResolver<ContentCardHeaderBaseProps>;
  Control?: ConfigResolver<ControlBaseProps<string>>;
  ControlGroup?: ConfigResolver<ControlGroupBaseProps>;
  DataCardLayout?: ConfigResolver<DataCardLayoutBaseProps>;
  DateInput?: ConfigResolver<DateInputBaseProps>;
  DatePicker?: ConfigResolver<DatePickerBaseProps>;
  Divider?: ConfigResolver<DividerBaseProps>;
  Dropdown?: ConfigResolver<DropdownBaseProps>;
  DotCount?: ConfigResolver<DotCountBaseProps>;
  DotStatusColor?: ConfigResolver<DotStatusColorBaseProps>;
  DotSymbol?: ConfigResolver<DotSymbolBaseProps>;
  Fallback?: ConfigResolver<FallbackBaseProps>;
  FocusTrap?: ConfigResolver<FocusTrapBaseProps>;
  FullscreenAlert?: ConfigResolver<FullscreenAlertBaseProps>;
  FullscreenModal?: ConfigResolver<FullscreenModalBaseProps>;
  FullscreenModalHeader?: ConfigResolver<FullscreenModalHeaderBaseProps>;
  FullscreenModalLayout?: ConfigResolver<FullscreenModalLayoutBaseProps>;
  HandleBar?: ConfigResolver<HandleBarBaseProps>;
  Icon?: ConfigResolver<IconBaseProps>;
  IconButton?: ConfigResolver<IconButtonBaseProps>;
  IconCounterButton?: ConfigResolver<IconCounterButtonBaseProps>;
  InputChip?: ConfigResolver<InputChipBaseProps>;
  InputStack?: ConfigResolver<InputStackBaseProps>;
  Interactable?: ConfigResolver<InteractableBaseProps>;
  LikeButton?: ConfigResolver<LikeButtonBaseProps>;
  Link?: ConfigResolver<LinkBaseProps>;
  ListCell?: ConfigResolver<ListCellBaseProps>;
  ListCellFallback?: ConfigResolver<ListCellFallbackBaseProps>;
  MediaCard?: ConfigResolver<MediaCardBaseProps>;
  MediaCardLayout?: ConfigResolver<MediaCardLayoutBaseProps>;
  MediaChip?: ConfigResolver<MediaChipBaseProps>;
  MessagingCard?: ConfigResolver<MessagingCardBaseProps>;
  Modal?: ConfigResolver<ModalBaseProps>;
  ModalBody?: ConfigResolver<ModalBodyBaseProps>;
  ModalFooter?: ConfigResolver<ModalFooterBaseProps>;
  ModalHeader?: ConfigResolver<ModalHeaderBaseProps>;
  ModalWrapper?: ConfigResolver<ModalWrapperBaseProps>;
  MultiContentModule?: ConfigResolver<MultiContentModuleBaseProps>;
  NavigationBar?: ConfigResolver<NavigationBarBaseProps>;
  NavigationTitle?: ConfigResolver<NavigationTitleBaseProps>;
  NavigationTitleSelect?: ConfigResolver<NavigationTitleSelectBaseProps>;
  Overlay?: ConfigResolver<OverlayBaseProps>;
  PageFooter?: ConfigResolver<PageFooterBaseProps>;
  PageHeader?: ConfigResolver<PageHeaderBaseProps>;
  Pagination?: ConfigResolver<PaginationBaseProps>;
  ProgressBar?: ConfigResolver<ProgressBarBaseProps>;
  ProgressBarWithFixedLabels?: ConfigResolver<ProgressBarWithFixedLabelsBaseProps>;
  ProgressBarWithFloatLabel?: ConfigResolver<ProgressBarWithFloatLabelBaseProps>;
  ProgressCircle?: ConfigResolver<ProgressCircleBaseProps>;
  Radio?: ConfigResolver<RadioBaseProps<string>>;
  RadioCell?: ConfigResolver<RadioCellBaseProps<string>>;
  RemoteImage?: ConfigResolver<RemoteImageBaseProps>;
  RemoteImageGroup?: ConfigResolver<RemoteImageGroupBaseProps>;
  RollingNumber?: ConfigResolver<RollingNumberBaseProps>;
  SearchInput?: ConfigResolver<SearchInputBaseProps>;
  SegmentedTab?: ConfigResolver<SegmentedTabBaseProps>;
  SegmentedTabs?: ConfigResolver<SegmentedTabsBaseProps>;
  SectionHeader?: ConfigResolver<SectionHeaderBaseProps>;
  Select?: ConfigResolver<AlphaSelectBaseProps>;
  SelectChip?: ConfigResolver<SelectChipBaseProps>;
  SelectOption?: ConfigResolver<SelectOptionBaseProps>;
  Switch?: ConfigResolver<SwitchBaseProps>;
  Shake?: ConfigResolver<ShakeBaseProps>;
  Sidebar?: ConfigResolver<SidebarBaseProps>;
  SidebarItem?: ConfigResolver<SidebarItemBaseProps>;
  SidebarMoreMenu?: ConfigResolver<SidebarMoreMenuBaseProps>;
  Spacer?: ConfigResolver<SpacerBaseProps>;
  Spinner?: ConfigResolver<SpinnerBaseProps>;
  Stepper?: ConfigResolver<StepperBaseProps>;
  TabIndicator?: ConfigResolver<TabIndicatorBaseProps>;
  TabLabel?: ConfigResolver<TabLabelBaseProps>;
  Table?: ConfigResolver<TableBaseProps>;
  TableBody?: ConfigResolver<TableBodyBaseProps>;
  TableCaption?: ConfigResolver<TableCaptionBaseProps>;
  TableCell?: ConfigResolver<TableCellBaseProps>;
  TableCellFallback?: ConfigResolver<TableCellFallbackBaseProps>;
  TableFooter?: ConfigResolver<TableFooterBaseProps>;
  TableHeader?: ConfigResolver<TableHeaderBaseProps>;
  TableRow?: ConfigResolver<TableRowBaseProps>;
  Tabs?: ConfigResolver<TabsBaseProps>;
  Tag?: ConfigResolver<TagBaseProps>;
  TextInput?: ConfigResolver<TextInputBaseProps>;
  Tile?: ConfigResolver<TileBaseProps>;
  TileButton?: ConfigResolver<TileButtonBaseProps>;
  Tooltip?: ConfigResolver<TooltipBaseProps>;
  TooltipContent?: ConfigResolver<TooltipContentBaseProps>;
  Toast?: ConfigResolver<ToastBaseProps>;
  Tour?: ConfigResolver<TourBaseProps>;
  Tray?: ConfigResolver<TrayBaseProps>;
};
