import type { AccordionBaseProps } from '../accordion/Accordion';
import type {
  AccordionHeaderBaseProps,
  AccordionIconBaseProps,
  AccordionMediaBaseProps,
  AccordionTitleBaseProps,
} from '../accordion/AccordionHeader';
import type { AccordionItemBaseProps } from '../accordion/AccordionItem';
import type { AccordionPanelBaseProps } from '../accordion/AccordionPanel';
import type { ComboboxBaseProps } from '../alpha/combobox/Combobox';
import type { DataCardBaseProps } from '../alpha/data-card/DataCard';
import type { DataCardLayoutBaseProps } from '../alpha/data-card/DataCardLayout';
import type { AlphaSelectBaseProps } from '../alpha/select/Select';
import type { SelectChipBaseProps } from '../alpha/select-chip/SelectChip';
import type { TabbedChipsBaseProps } from '../alpha/tabbed-chips/TabbedChips';
import type { LottieStatusAnimationBaseProps } from '../animation/LottieStatusAnimation';
import type { LottieBaseProps } from '../animation/types';
import type { BannerBaseProps } from '../banner/Banner';
import type { ButtonBaseProps } from '../buttons/Button';
import type { ButtonGroupBaseProps } from '../buttons/ButtonGroup';
import type { IconButtonBaseProps } from '../buttons/IconButton';
import type { IconCounterButtonBaseProps } from '../buttons/IconCounterButton';
import type { SlideButtonBaseProps } from '../buttons/SlideButton';
import type { CardBaseProps } from '../cards/Card';
import type { CardBodyBaseProps } from '../cards/CardBody';
import type { CardFooterBaseProps } from '../cards/CardFooter';
import type { CardGroupBaseProps } from '../cards/CardGroup';
import type { CardRootBaseProps } from '../cards/CardRoot';
import type { ContentCardBaseProps } from '../cards/ContentCard/ContentCard';
import type { ContentCardBodyBaseProps } from '../cards/ContentCard/ContentCardBody';
import type { ContentCardFooterBaseProps } from '../cards/ContentCard/ContentCardFooter';
import type { ContentCardHeaderBaseProps } from '../cards/ContentCard/ContentCardHeader';
import type { LikeButtonBaseProps } from '../cards/LikeButton';
import type { MediaCardBaseProps } from '../cards/MediaCard/index';
import type { MessagingCardBaseProps } from '../cards/MessagingCard/index';
import type { CarouselBaseProps } from '../carousel/Carousel';
import type { CellBaseProps } from '../cells/Cell';
import type { ListCellBaseProps } from '../cells/ListCell';
import type { ListCellFallbackBaseProps } from '../cells/ListCellFallback';
import type { ChipBaseProps } from '../chips/ChipProps';
import type { InputChipBaseProps } from '../chips/InputChip';
import type { MediaChipBaseProps } from '../chips/MediaChip';
import type { CoachmarkBaseProps } from '../coachmark/Coachmark';
import type { CollapsibleBaseProps } from '../collapsible/Collapsible';
import type { CheckboxBaseProps } from '../controls/Checkbox';
import type { CheckboxCellBaseProps } from '../controls/CheckboxCell';
import type { ControlBaseProps } from '../controls/Control';
import type { ControlGroupBaseProps } from '../controls/ControlGroup';
import type { InputStackBaseProps } from '../controls/InputStack';
import type { RadioBaseProps } from '../controls/Radio';
import type { RadioCellBaseProps } from '../controls/RadioCell';
import type { SearchInputBaseProps } from '../controls/SearchInput';
import type { SelectOptionBaseProps } from '../controls/SelectOption';
import type { SwitchBaseProps } from '../controls/Switch';
import type { TextInputBaseProps } from '../controls/TextInput';
import type { DateInputBaseProps } from '../dates/DateInput';
import type { DatePickerBaseProps } from '../dates/DatePicker';
import type { DotCountBaseProps } from '../dots/DotCount';
import type { DotStatusColorBaseProps } from '../dots/DotStatusColor';
import type { DotSymbolBaseProps } from '../dots/DotSymbol';
import type { IconBaseProps } from '../icons/Icon';
import type { LogoMarkBaseProps } from '../icons/LogoMark';
import type { LogoWordmarkBaseProps } from '../icons/LogoWordmark';
import type { SubBrandLogoMarkBaseProps } from '../icons/SubBrandLogoMark';
import type { SubBrandLogoWordmarkBaseProps } from '../icons/SubBrandLogoWordmark';
import type { HeroSquareBaseProps } from '../illustrations/HeroSquare';
import type { PictogramBaseProps } from '../illustrations/Pictogram';
import type { SpotIconBaseProps } from '../illustrations/SpotIcon';
import type { SpotRectangleBaseProps } from '../illustrations/SpotRectangle';
import type { SpotSquareBaseProps } from '../illustrations/SpotSquare';
import type { BoxBaseProps } from '../layout/Box';
import type { DividerBaseProps } from '../layout/Divider';
import type { FallbackBaseProps } from '../layout/Fallback';
import type { SpacerBaseProps } from '../layout/Spacer';
import type { AvatarBaseProps } from '../media/Avatar';
import type { RemoteImageBaseProps } from '../media/RemoteImage';
import type { RemoteImageGroupBaseProps } from '../media/RemoteImageGroup';
import type { AnimatedCaretBaseProps } from '../motion/AnimatedCaret';
import type { ColorSurgeBaseProps } from '../motion/ColorSurge';
import type { PulseBaseProps } from '../motion/Pulse';
import type { ShakeBaseProps } from '../motion/Shake';
import type { MultiContentModuleBaseProps } from '../multi-content-module/MultiContentModule';
import type { BrowserBarBaseProps } from '../navigation/BrowserBar';
import type { NavigationTitleBaseProps } from '../navigation/NavigationTitle';
import type { NavigationTitleSelectBaseProps } from '../navigation/NavigationTitleSelect';
import type { TopNavBarBaseProps } from '../navigation/TopNavBar';
import type { RollingNumberBaseProps } from '../numbers/RollingNumber/RollingNumber';
import type { NumpadBaseProps } from '../numpad/Numpad';
import type { AlertBaseProps } from '../overlays/Alert';
import type { DrawerBaseProps } from '../overlays/drawer/Drawer';
import type { ModalBaseProps } from '../overlays/modal/Modal';
import type { ModalBodyBaseProps } from '../overlays/modal/ModalBody';
import type { ModalFooterBaseProps } from '../overlays/modal/ModalFooter';
import type { ModalHeaderBaseProps } from '../overlays/modal/ModalHeader';
import type { OverlayBaseProps } from '../overlays/overlay/Overlay';
import type { PortalProviderBaseProps } from '../overlays/PortalProvider';
import type { ToastBaseProps } from '../overlays/Toast';
import type { TooltipBaseProps } from '../overlays/tooltip/Tooltip';
import type { TrayBaseProps } from '../overlays/tray/Tray';
import type { PageFooterBaseProps } from '../page/PageFooter';
import type { PageHeaderBaseProps } from '../page/PageHeader';
import type { StepperBaseProps } from '../stepper/Stepper';
import type { InteractableBaseProps } from '../system/Interactable';
import type { PressableBaseProps } from '../system/Pressable';
import type { SegmentedTabBaseProps } from '../tabs/SegmentedTab';
import type { SegmentedTabsBaseProps } from '../tabs/SegmentedTabs';
import type { TabIndicatorBaseProps } from '../tabs/TabIndicator';
import type { TabLabelBaseProps } from '../tabs/TabLabel';
import type { TabsBaseProps } from '../tabs/Tabs';
import type { TagBaseProps } from '../tag/Tag';
import type { TourBaseProps } from '../tour/Tour';
import type { LinkBaseProps } from '../typography/Link';
import type { TextBaseProps } from '../typography/Text';
import type { CounterBaseProps } from '../visualizations/Counter';
import type { ProgressBarBaseProps } from '../visualizations/ProgressBar';
import type { ProgressBarWithFixedLabelsBaseProps } from '../visualizations/ProgressBarWithFixedLabels';
import type { ProgressBarWithFloatLabelBaseProps } from '../visualizations/ProgressBarWithFloatLabel';
import type { ProgressCircleBaseProps } from '../visualizations/ProgressCircle';

/**
 * Config resolver that supports either static partial props object
 * or a function that receives component props and returns partial props.
 */
export type ConfigResolver<P> = Partial<P> | ((props: P) => Partial<P>);

/**
 * Component config for customization of default component props.
 * Use base props for config resolver typing so defaults are element-agnostic.
 */
export type ComponentConfig = {
  Accordion?: ConfigResolver<AccordionBaseProps>;
  AccordionHeader?: ConfigResolver<AccordionHeaderBaseProps>;
  AccordionIcon?: ConfigResolver<AccordionIconBaseProps>;
  AccordionItem?: ConfigResolver<AccordionItemBaseProps>;
  AccordionMedia?: ConfigResolver<AccordionMediaBaseProps>;
  AccordionPanel?: ConfigResolver<AccordionPanelBaseProps>;
  AccordionTitle?: ConfigResolver<AccordionTitleBaseProps>;
  Alert?: ConfigResolver<AlertBaseProps>;
  DataCard?: ConfigResolver<DataCardBaseProps>;
  TabbedChips?: ConfigResolver<TabbedChipsBaseProps>;
  AnimatedCaret?: ConfigResolver<AnimatedCaretBaseProps>;
  Avatar?: ConfigResolver<AvatarBaseProps>;
  Banner?: ConfigResolver<BannerBaseProps>;
  Box?: ConfigResolver<BoxBaseProps>;
  BrowserBar?: ConfigResolver<BrowserBarBaseProps>;
  Button?: ConfigResolver<ButtonBaseProps>;
  ButtonGroup?: ConfigResolver<ButtonGroupBaseProps>;
  Card?: ConfigResolver<CardBaseProps>;
  CardBody?: ConfigResolver<CardBodyBaseProps>;
  CardFooter?: ConfigResolver<CardFooterBaseProps>;
  CardGroup?: ConfigResolver<CardGroupBaseProps>;
  CardRoot?: ConfigResolver<CardRootBaseProps>;
  Carousel?: ConfigResolver<CarouselBaseProps>;
  Cell?: ConfigResolver<CellBaseProps>;
  Chip?: ConfigResolver<ChipBaseProps>;
  Checkbox?: ConfigResolver<CheckboxBaseProps<string>>;
  CheckboxCell?: ConfigResolver<CheckboxCellBaseProps<string>>;
  Coachmark?: ConfigResolver<CoachmarkBaseProps>;
  Collapsible?: ConfigResolver<CollapsibleBaseProps>;
  ColorSurge?: ConfigResolver<ColorSurgeBaseProps>;
  Combobox?: ConfigResolver<ComboboxBaseProps>;
  ContentCard?: ConfigResolver<ContentCardBaseProps>;
  ContentCardBody?: ConfigResolver<ContentCardBodyBaseProps>;
  ContentCardFooter?: ConfigResolver<ContentCardFooterBaseProps>;
  ContentCardHeader?: ConfigResolver<ContentCardHeaderBaseProps>;
  Control?: ConfigResolver<ControlBaseProps<string>>;
  ControlGroup?: ConfigResolver<ControlGroupBaseProps>;
  Counter?: ConfigResolver<CounterBaseProps>;
  DataCardLayout?: ConfigResolver<DataCardLayoutBaseProps>;
  DateInput?: ConfigResolver<DateInputBaseProps>;
  DatePicker?: ConfigResolver<DatePickerBaseProps>;
  Divider?: ConfigResolver<DividerBaseProps>;
  DotCount?: ConfigResolver<DotCountBaseProps>;
  DotStatusColor?: ConfigResolver<DotStatusColorBaseProps>;
  DotSymbol?: ConfigResolver<DotSymbolBaseProps>;
  Drawer?: ConfigResolver<DrawerBaseProps>;
  Fallback?: ConfigResolver<FallbackBaseProps>;
  HeroSquare?: ConfigResolver<HeroSquareBaseProps>;
  Icon?: ConfigResolver<IconBaseProps>;
  IconButton?: ConfigResolver<IconButtonBaseProps>;
  IconCounterButton?: ConfigResolver<IconCounterButtonBaseProps>;
  InputChip?: ConfigResolver<InputChipBaseProps>;
  InputStack?: ConfigResolver<InputStackBaseProps>;
  Interactable?: ConfigResolver<InteractableBaseProps>;
  LikeButton?: ConfigResolver<LikeButtonBaseProps>;
  Link?: ConfigResolver<LinkBaseProps>;
  ListCell?: ConfigResolver<ListCellBaseProps>;
  ListCellFallback?: ConfigResolver<ListCellFallbackBaseProps>;
  LogoMark?: ConfigResolver<LogoMarkBaseProps>;
  LogoWordmark?: ConfigResolver<LogoWordmarkBaseProps>;
  Lottie?: ConfigResolver<LottieBaseProps>;
  LottieStatusAnimation?: ConfigResolver<LottieStatusAnimationBaseProps>;
  MediaCard?: ConfigResolver<MediaCardBaseProps>;
  MediaChip?: ConfigResolver<MediaChipBaseProps>;
  MessagingCard?: ConfigResolver<MessagingCardBaseProps>;
  Modal?: ConfigResolver<ModalBaseProps>;
  ModalBody?: ConfigResolver<ModalBodyBaseProps>;
  ModalFooter?: ConfigResolver<ModalFooterBaseProps>;
  ModalHeader?: ConfigResolver<ModalHeaderBaseProps>;
  MultiContentModule?: ConfigResolver<MultiContentModuleBaseProps>;
  NavigationTitle?: ConfigResolver<NavigationTitleBaseProps>;
  NavigationTitleSelect?: ConfigResolver<NavigationTitleSelectBaseProps>;
  Numpad?: ConfigResolver<NumpadBaseProps>;
  Overlay?: ConfigResolver<OverlayBaseProps>;
  PageFooter?: ConfigResolver<PageFooterBaseProps>;
  PageHeader?: ConfigResolver<PageHeaderBaseProps>;
  Pictogram?: ConfigResolver<PictogramBaseProps>;
  PortalProvider?: ConfigResolver<PortalProviderBaseProps>;
  Pressable?: ConfigResolver<PressableBaseProps>;
  ProgressBar?: ConfigResolver<ProgressBarBaseProps>;
  ProgressBarWithFixedLabels?: ConfigResolver<ProgressBarWithFixedLabelsBaseProps>;
  ProgressBarWithFloatLabel?: ConfigResolver<ProgressBarWithFloatLabelBaseProps>;
  ProgressCircle?: ConfigResolver<ProgressCircleBaseProps>;
  Pulse?: ConfigResolver<PulseBaseProps>;
  Radio?: ConfigResolver<RadioBaseProps<string>>;
  RadioCell?: ConfigResolver<RadioCellBaseProps<string>>;
  RemoteImage?: ConfigResolver<RemoteImageBaseProps>;
  RemoteImageGroup?: ConfigResolver<RemoteImageGroupBaseProps>;
  RollingNumber?: ConfigResolver<RollingNumberBaseProps>;
  SearchInput?: ConfigResolver<SearchInputBaseProps>;
  SegmentedTab?: ConfigResolver<SegmentedTabBaseProps>;
  SegmentedTabs?: ConfigResolver<SegmentedTabsBaseProps>;
  Select?: ConfigResolver<AlphaSelectBaseProps>;
  SelectChip?: ConfigResolver<SelectChipBaseProps>;
  SelectOption?: ConfigResolver<SelectOptionBaseProps>;
  Shake?: ConfigResolver<ShakeBaseProps>;
  SlideButton?: ConfigResolver<SlideButtonBaseProps>;
  Spacer?: ConfigResolver<SpacerBaseProps>;
  SpotIcon?: ConfigResolver<SpotIconBaseProps>;
  SpotRectangle?: ConfigResolver<SpotRectangleBaseProps>;
  SpotSquare?: ConfigResolver<SpotSquareBaseProps>;
  Stepper?: ConfigResolver<StepperBaseProps>;
  SubBrandLogoMark?: ConfigResolver<SubBrandLogoMarkBaseProps>;
  SubBrandLogoWordmark?: ConfigResolver<SubBrandLogoWordmarkBaseProps>;
  Switch?: ConfigResolver<SwitchBaseProps<string>>;
  TabIndicator?: ConfigResolver<TabIndicatorBaseProps>;
  TabLabel?: ConfigResolver<TabLabelBaseProps>;
  Tabs?: ConfigResolver<TabsBaseProps>;
  Tag?: ConfigResolver<TagBaseProps>;
  Text?: ConfigResolver<TextBaseProps>;
  TextInput?: ConfigResolver<TextInputBaseProps>;
  Toast?: ConfigResolver<ToastBaseProps>;
  TopNavBar?: ConfigResolver<TopNavBarBaseProps>;
  Tour?: ConfigResolver<TourBaseProps>;
  Tray?: ConfigResolver<TrayBaseProps>;
  Tooltip?: ConfigResolver<TooltipBaseProps>;
};
