plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/huntercopp/sources/cds/apps/docs/dist"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/huntercopp/sources/cds/apps/docs"
command = "# No build needed - using pre-built files"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]